
CREATE TABLE IF NOT EXISTS schedtable (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    day VARCHAR(255) NOT NULL,
    start_at VARCHAR(255) NOT NULL,
    end_at VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS usertable (
    id SERIAL PRIMARY KEY,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);